### ISSUE TITLE
question

### ISSUE THREAD

**Issue by zhu2014yi** [shallowtoil/DROL#1]
想问一下代码啥时候能开源呢？

**Comment by shallowtoil** [comment]
I'm planing to release the code at November.

**Comment by zhu2014yi** [comment]
hi jinghao!
非常感谢百忙之中能查看这封信，你的论文写的很精彩，但是在这之中我还是有些细节没法很好把握，很想研读你的代码细节，现在也已经是11月底了，是否打算在这两天开源你的代码?
best！

在 2019年10月19日星期六，Jinghao Zhou <notifications@github.com> 写道：

**Comment by shallowtoil** [comment]
Hi,


Sorry for my words. I WAS orginally planning to release the code at the end of November, but my tutor later told me that I shall not release it now. The whole framework is relatively straitforward though, you may try to implement yourself. If you have any questions, I'm very happy to help you with it.


Regrads,
Jensen




------------------ Original ------------------

**Comment by zhu2014yi** [comment]
我不是很清楚你在你的算法里面的裁剪方式，因为atom的裁剪函数(sample_patch)和pysot的裁剪函数（get_subwindows）不一样的，你是怎么选择的。另外如果方便的话可否加我微信聊(微信号:
wxid_p06nz8ojbb3o22 )，不方便也没事的。我就在信上面请教一下了。


在 2019年12月2日星期一，Jinghao Zhou <notifications@github.com> 写道：

**Comment by zhu2014yi** [comment]
我不是很清楚你在你的算法里面的裁剪方式，因为atom的裁剪函数(sample_patch)和pysot的裁剪函数（get_subwindows）
不一样的，你是怎么选择的。另外如果方便的话可否加我微信聊，不方便也没事的(微信号:wxid_p06nz8ojbb3o22)。我就在信上面请教一下。

在 2019年12月2日星期一，Jinghao Zhou <notifications@github.com> 写道：

**Comment by shallowtoil** [comment]
Hi, 


As discribed in paper, we use the 255*255 search area similar to siamese network setting as the input for online classification subnet. We do not use sample_patch in ATOM.


Regrads,
Jensen


------------------ Original ------------------

**Comment by zhu2014yi** [comment]
hi jinghao，
另外在模板更新那一块儿，你的z’ 选择是根据下面的公式(8)来的，其中的
[image: image.png][image:
image.png]我不是很理解，我的理解是代表第N帧中用Zs作为模板和第N帧中的搜索区域卷积得到的最大的score得分，和相应的边框，还有一个Z1就是用第一帧作为模板和第N帧中的搜索区域做卷积得到的最大的score和相应的边框，那在跟踪部分初始化参数之后在def
track()这个函数里面岂不是要算两次分类得分和相应的回归得分，一次是第一帧的模板和第N帧搜索区域做卷积得到score和reg，还有一次是Zs和第N帧搜索区域做卷积得到score和reg？可以说一下你当时的思路吗？
[image: image.png]
期待回复！
祝好！

Jinghao Zhou <notifications@github.com> 于2019年12月4日周三 下午11:18写道：

**Comment by shallowtoil** [comment]
The code is now available!

**Comment by zhu2014yi** [comment]
> The code is now available!

thanks
