### ISSUE TITLE
where is the "warp(.)" operation like formula 6

### ISSUE THREAD

**Issue by laisimiao** [shallowtoil/DROL#11]
As you paper says:
![image](https://user-images.githubusercontent.com/37405764/123190309-e62e9d00-d4d1-11eb-9376-0acc8143f6c1.png)
`where warp(·) is the cropping operation to feature size of the template `, could you help me point out where it is in codes?

**Comment by jensenzhoujh** [comment]
Hi, warp(·) is implemented with self.get_subwindow(·) as in https://github.com/shallowtoil/DROL/blob/4aebe575394bc035e9924c8711c7d5d76bfef37a/pysot/tracker/siamrpn_tracker.py#L213

**Comment by laisimiao** [comment]
Oh just so simple? But it's a bit mysterious described in paper as it's like a cropping operation for index return by `arg` operation?
